/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { SendToFallback } from "../SendToFallback";

export class SendToFallback__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SendToFallback> {
    return super.deploy(overrides || {}) as Promise<SendToFallback>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SendToFallback {
    return super.attach(address) as SendToFallback;
  }
  connect(signer: Signer): SendToFallback__factory {
    return super.connect(signer) as SendToFallback__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SendToFallback {
    return new Contract(address, _abi, signerOrProvider) as SendToFallback;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_to",
        type: "address",
      },
    ],
    name: "callFallback",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_to",
        type: "address",
      },
    ],
    name: "transferToFallback",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102e0806100206000396000f3fe6080604052600436106100295760003560e01c80636ba87a531461002e578063cfc6cdaa1461004a575b600080fd5b61004860048036038101906100439190610175565b610066565b005b610064600480360381019061005f9190610175565b610116565b005b60008173ffffffffffffffffffffffffffffffffffffffff163460405161008c906101e4565b60006040518083038185875af1925050503d80600081146100c9576040519150601f19603f3d011682016040523d82523d6000602084013e6100ce565b606091505b5050905080610112576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610109906101f9565b60405180910390fd5b5050565b8073ffffffffffffffffffffffffffffffffffffffff166108fc349081150290604051600060405180830381858888f1935050505015801561015c573d6000803e3d6000fd5b5050565b60008135905061016f81610293565b92915050565b60006020828403121561018757600080fd5b600061019584828501610160565b91505092915050565b60006101ab601483610224565b91506101b682610267565b602082019050919050565b60006101ce600083610219565b91506101d982610290565b600082019050919050565b60006101ef826101c1565b9150819050919050565b600060208201905081810360008301526102128161019e565b9050919050565b600081905092915050565b600082825260208201905092915050565b600061024082610247565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b7f4661696c656420746f2073656e64204574686572000000000000000000000000600082015250565b50565b61029c81610235565b81146102a757600080fd5b5056fea26469706673582212208a3beca2256902941915b3d64bc7e39335898eb25c8c1a7bfe023e2d2e99096764736f6c63430008030033";
