/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { MyContract } from "./MyContract";
export type { MyContract2 } from "./MyContract2";
export type { OwnedUpgradeabilityProxy } from "./OwnedUpgradeabilityProxy";

export { Ownable__factory } from "./factories/Ownable__factory";
export { MyContract__factory } from "./factories/MyContract__factory";
export { MyContract2__factory } from "./factories/MyContract2__factory";
export { OwnedUpgradeabilityProxy__factory } from "./factories/OwnedUpgradeabilityProxy__factory";
